// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh5eTF9zV_U0zZzBpkZVfAekLODaUiduE',
    appId: '1:331436826284:web:5d83fdd225c0bf5daa4909',
    messagingSenderId: '331436826284',
    projectId: 'nainafutsalapp',
    authDomain: 'nainafutsalapp.firebaseapp.com',
    storageBucket: 'nainafutsalapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyAJFSVEzJwrNBMabCRVshrWMQJDozPvxBg',
    // appId: '1:331436826284:android:9fdac7ffb2f90e17aa4909',
    // messagingSenderId: '331436826284',
    // projectId: 'nainafutsalapp',
    // storageBucket: 'nainafutsalapp.appspot.com',
    apiKey: 'AIzaSyCAeq9a-mLZfXN7_DQUL3n_fKVByc6J6ak',
appId: '1:331436826284:android:9fdac7ffb2f90e17aa4909',
messagingSenderId: '331436826284',
projectId: 'futsal-booking-app-b4221',
storageBucket: 'futsal-booking-app-b4221.appspot.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdeC-DZ2PPBHD1Pfg1vkFJ-IFUac0D9ks',
    appId: '1:331436826284:ios:614388b5ac1bff47aa4909',
    messagingSenderId: '331436826284',
    projectId: 'nainafutsalapp',
    storageBucket: 'nainafutsalapp.appspot.com',
    iosBundleId: 'com.example.futsalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdeC-DZ2PPBHD1Pfg1vkFJ-IFUac0D9ks',
    appId: '1:331436826284:ios:3e5778140148e79baa4909',
    messagingSenderId: '331436826284',
    projectId: 'nainafutsalapp',
    storageBucket: 'nainafutsalapp.appspot.com',
    iosBundleId: 'com.example.futsalApp.RunnerTests',
  );
}
